apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: deploy-webserver
    # Annotations are use for documentation e.g
    # Store buid/release ids, pr numbers, git branch, etc
    annotations:
        description: Deployment for nginx webserver
spec:
    replicas: 3
    template:
        metadata:
            labels:
                app: webserver
        spec:
            containers:
            - name: webserver
              image: nginx:alpine
              ports:
              - containerPort: 80
                name: webserver-port
            #   volumeMounts:
            #   - name: hostvol
            #     mounthPath: /usr/share/nginx/html
            # volumes:
            # - name: hostvol
            #   hostPath:
            #     path: /home/docker/vol
